version: '3.8'

services:
  # MinIO Object Storage
  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      MINIO_ROOT_USER: murmax
      MINIO_ROOT_PASSWORD: rootroot
    volumes:
      - ./minio-data:/data
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgress
    environment:
      - POSTGRES_USER=ADMIN
      - POSTGRES_PASSWORD=ADMIN
    volumes:
      # This saves the database data to a 'postgres-data' folder
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  
  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "8087:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    networks:
      - app-network


  # Redis Cache & Queue
  cache:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - app-network
    restart: unless-stopped

# Define the shared network
networks:
  app-network:
    driver: bridge
