version: '3.7'

services:
  # MinIO Object Storage
  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      MINIO_ROOT_USER: murmax
      MINIO_ROOT_PASSWORD: rootroot
    volumes:
      - ./minio-data:/data
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase       # Database name
      POSTGRES_USER: murmax         # Database user
      POSTGRES_PASSWORD: rootroot   # Database password
    ports:
      - 5432:5432
    volumes:
      # This saves the database data to a 'postgres-data' folder
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # Redis Cache & Queue
  cache:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - app-network
    restart: unless-stopped

# Define the shared network
networks:
  app-network:
    driver: bridge
