services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgress
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/datas
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge